# Generated by Django 6.1 on 2026-09-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='project_type',
            field=models.CharField(choices=[('website', 'Veb-sayt'), ('telegram_bot', 'Telegram Bot'), ('mobile_app', 'Mobil Ilova'), ('saas', 'SaaS'), ('ecommerce', 'E-Commerce'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Loyiha turi'),
        ),
    ]
