# Generated by Django 6.1 on 2026-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_startup_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='app_store_link',
            field=models.URLField(blank=True, null=True, verbose_name='App Store Havolasi'),
        ),
        migrations.AddField(
            model_name='startup',
            name='bot_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bot Username'),
        ),
        migrations.AddField(
            model_name='startup',
            name='play_store_link',
            field=models.URLField(blank=True, null=True, verbose_name='Play Store Havolasi'),
        ),
    ]
