# Generated by Django 6.1 on 2026-09-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Sotildi'),
        ),
    ]
